<a href="https://colab.research.google.com/github/iabbakr/Hamoyeee/blob/master/quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url = '/content/drive/MyDrive/Colab Notebooks/FoodBalanceSheets_E_Africa_NOFLAG.csv'
csv_df = pd.read_csv(url, encoding="latin-1", error_bad_lines=False)
csv_df.to_csv(url)

csv_df.describe(include='all')

<ipython-input-2-9cbe6604552f>:6: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  csv_df = pd.read_csv(url, encoding="latin-1", error_bad_lines=False)

,Unnamed: 0.1,Unnamed: 0,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
count,60942.000000,60942.000000,60942.000000,60942,60942.000000,60941,60941,60940,60940,59354.000000,59394.000000,59405.000000,59436.000000,59506.000000
unique,NaN,NaN,NaN,50,NaN,120,19,18,5,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,Kenya,NaN,Milk - Excluding Butter,5301,Domestic supply quantity,1000 tonnes,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,1560,NaN,1262,5295,5295,40930,NaN,NaN,NaN,NaN,NaN
mean,30470.500000,30470.500000,134.282088,NaN,2691.453431,NaN,NaN,NaN,NaN,134.196282,135.238243,136.562119,140.920136,143.760797
std,17592.584389,17592.584389,72.692510,NaN,1052.588963,NaN,NaN,NaN,NaN,1567.663696,1603.417386,1640.048318,1671.876324,1710.796932
min,0.000000,0.000000,4.000000,NaN,2501.000000,NaN,NaN,NaN,NaN,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,15235.250000,15235.250000,74.000000,NaN,2562.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,30470.500000,30470.500000,136.000000,NaN,2630.000000,NaN,NaN,NaN,NaN,0.090000,0.080000,0.080000,0.100000,0.070000
75%,45705.750000,45705.750000,195.000000,NaN,2775.000000,NaN,NaN,NaN,NaN,8.340000,8.460000,8.430000,9.000000,9.000000
max,60941.000000,60941.000000,1014.000000,NaN,260000.000000,NaN,NaN,NaN,NaN,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [ ]:
csv_df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [ ]:
csv_df.groupby('Y2016')['Y2017'].describe()

,count,mean,std,min,25%,50%,75%,max
Y2016,,,,,,,,
-3225.0,1.0,689.0,NaN,689.0,689.0,689.0,689.0,689.0
-2051.0,1.0,206.0,NaN,206.0,206.0,206.0,206.0,206.0
-1499.0,1.0,2665.0,NaN,2665.0,2665.0,2665.0,2665.0,2665.0
-1324.0,1.0,2555.0,NaN,2555.0,2555.0,2555.0,2555.0,2555.0
-1088.0,1.0,457.0,NaN,457.0,457.0,457.0,457.0,457.0
...,...,...,...,...,...,...,...,...
94447.0,1.0,96443.0,NaN,96443.0,96443.0,96443.0,96443.0,96443.0
103603.0,1.0,106400.0,NaN,106400.0,106400.0,106400.0,106400.0,106400.0
116483.0,1.0,112625.0,NaN,112625.0,112625.0,112625.0,112625.0,112625.0
119330.0,1.0,117702.0,NaN,117702.0,117702.0,117702.0,117702.0,117702.0
185960.0,1.0,190873.0,NaN,190873.0,190873.0,190873.0,190873.0,190873.0

In [ ]:
csv_df.head()

,Unnamed: 0.1,Unnamed: 0,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,0,0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,1,1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,2,2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,3,3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [ ]:
csv_df.groupby('Y2017')['Area'].sum()

Y2017
-1582.0                       EgyptEgypt
-1200.0                       Mozambique
-1159.0                       Mozambique
-865.0       United Republic of Tanzania
-860.0       United Republic of Tanzania
                        ...
 96443.0                           Egypt
 106400.0                       Ethiopia
 112625.0                        Nigeria
 117702.0                        Nigeria
 190873.0                        Nigeria
Name: Area, Length: 4537, dtype: object

In [ ]:
csv_df.groupby('Y2017')['Area'].describe()

          count unique                          top freq
Y2017
-1582.0       2      1                        Egypt    2
-1200.0       1      1                   Mozambique    1
-1159.0       1      1                   Mozambique    1
-865.0        1      1  United Republic of Tanzania    1
-860.0        1      1  United Republic of Tanzania    1
...         ...    ...                          ...  ...
 96443.0      1      1                        Egypt    1
 106400.0     1      1                     Ethiopia    1
 112625.0     1      1                      Nigeria    1
 117702.0     1      1                      Nigeria    1
 190873.0     1      1                      Nigeria    1

[4537 rows x 4 columns]

In [ ]:
csv_df.groupby('Y2014').describe()

          Unnamed: 0.1                                                         \
                 count     mean       std      min      25%      50%      75%
Y2014
-1796.0            1.0  44050.0       NaN  44050.0  44050.0  44050.0  44050.0
-1631.0            1.0  44013.0       NaN  44013.0  44013.0  44013.0  44013.0
-849.0             2.0  33841.0  4.242641  33838.0  33839.5  33841.0  33842.5
-838.0             1.0  44603.0       NaN  44603.0  44603.0  44603.0  44603.0
-685.0             1.0  37479.0       NaN  37479.0  37479.0  37479.0  37479.0
...                ...      ...       ...      ...      ...      ...      ...
 90425.0           1.0   8859.0       NaN   8859.0   8859.0   8859.0   8859.0
 98094.0           1.0  11631.0       NaN  11631.0  11631.0  11631.0  11631.0
 108756.0          1.0  43132.0       NaN  43132.0  43132.0  43132.0  43132.0
 109593.0          1.0  43128.0       NaN  43128.0  43128.0  43128.0  43128.0
 176405.0          1.0  42972.0       NaN  42972.0  42972.0  42972.0  42972.0

                   Unnamed: 0           ...     Y2017           Y2018  \
               max      count     mean  ...       75%       max count
Y2014                                   ...
-1796.0    44050.0        1.0  44050.0  ...       0.0       0.0   1.0
-1631.0    44013.0        1.0  44013.0  ...    -689.0    -689.0   1.0
-849.0     33844.0        2.0  33841.0  ...    -600.0    -600.0   2.0
-838.0     44603.0        1.0  44603.0  ...    -538.0    -538.0   1.0
-685.0     37479.0        1.0  37479.0  ...     689.0     689.0   1.0
...            ...        ...      ...  ...       ...       ...   ...
 90425.0    8859.0        1.0   8859.0  ...   96443.0   96443.0   1.0
 98094.0   11631.0        1.0  11631.0  ...  106400.0  106400.0   1.0
 108756.0  43132.0        1.0  43132.0  ...  112625.0  112625.0   1.0
 109593.0  43128.0        1.0  43128.0  ...  117702.0  117702.0   1.0
 176405.0  42972.0        1.0  42972.0  ...  190873.0  190873.0   1.0


               mean  std       min       25%       50%       75%       max
Y2014
-1796.0         0.0  NaN       0.0       0.0       0.0       0.0       0.0
-1631.0         5.0  NaN       5.0       5.0       5.0       5.0       5.0
-849.0       -598.0  0.0    -598.0    -598.0    -598.0    -598.0    -598.0
-838.0       -567.0  NaN    -567.0    -567.0    -567.0    -567.0    -567.0
-685.0        399.0  NaN     399.0     399.0     399.0     399.0     399.0
...             ...  ...       ...       ...       ...       ...       ...
 90425.0    98424.0  NaN   98424.0   98424.0   98424.0   98424.0   98424.0
 98094.0   109224.0  NaN  109224.0  109224.0  109224.0  109224.0  109224.0
 108756.0  117038.0  NaN  117038.0  117038.0  117038.0  117038.0  117038.0
 109593.0  118172.0  NaN  118172.0  118172.0  118172.0  118172.0  118172.0
 176405.0  195875.0  NaN  195875.0  195875.0  195875.0  195875.0  195875.0

[4493 rows x 64 columns]

In [ ]:
csv_df.groupby('Y2015').describe()

          Unnamed: 0.1                                                   \
                 count     mean std      min      25%      50%      75%
Y2015
-3161.0            1.0  49834.0 NaN  49834.0  49834.0  49834.0  49834.0
-2152.0            1.0  49894.0 NaN  49894.0  49894.0  49894.0  49894.0
-1284.0            1.0  51233.0 NaN  51233.0  51233.0  51233.0  51233.0
-907.0             1.0  58111.0 NaN  58111.0  58111.0  58111.0  58111.0
-887.0             1.0  51337.0 NaN  51337.0  51337.0  51337.0  51337.0
...                ...      ...  ..      ...      ...      ...      ...
 92443.0           1.0   8859.0 NaN   8859.0   8859.0   8859.0   8859.0
 100835.0          1.0  11631.0 NaN  11631.0  11631.0  11631.0  11631.0
 110798.0          1.0  43132.0 NaN  43132.0  43132.0  43132.0  43132.0
 111663.0          1.0  43128.0 NaN  43128.0  43128.0  43128.0  43128.0
 181137.0          1.0  42972.0 NaN  42972.0  42972.0  42972.0  42972.0

                   Unnamed: 0           ...     Y2017           Y2018  \
               max      count     mean  ...       75%       max count
Y2015                                   ...
-3161.0    49834.0        1.0  49834.0  ...    2665.0    2665.0   1.0
-2152.0    49894.0        1.0  49894.0  ...    2555.0    2555.0   1.0
-1284.0    51233.0        1.0  51233.0  ...    -607.0    -607.0   1.0
-907.0     58111.0        1.0  58111.0  ...     532.0     532.0   1.0
-887.0     51337.0        1.0  51337.0  ...    -819.0    -819.0   1.0
...            ...        ...      ...  ...       ...       ...   ...
 92443.0    8859.0        1.0   8859.0  ...   96443.0   96443.0   1.0
 100835.0  11631.0        1.0  11631.0  ...  106400.0  106400.0   1.0
 110798.0  43132.0        1.0  43132.0  ...  112625.0  112625.0   1.0
 111663.0  43128.0        1.0  43128.0  ...  117702.0  117702.0   1.0
 181137.0  42972.0        1.0  42972.0  ...  190873.0  190873.0   1.0


               mean std       min       25%       50%       75%       max
Y2015
-3161.0      -296.0 NaN    -296.0    -296.0    -296.0    -296.0    -296.0
-2152.0      -597.0 NaN    -597.0    -597.0    -597.0    -597.0    -597.0
-1284.0      1898.0 NaN    1898.0    1898.0    1898.0    1898.0    1898.0
-907.0       -529.0 NaN    -529.0    -529.0    -529.0    -529.0    -529.0
-887.0        163.0 NaN     163.0     163.0     163.0     163.0     163.0
...             ...  ..       ...       ...       ...       ...       ...
 92443.0    98424.0 NaN   98424.0   98424.0   98424.0   98424.0   98424.0
 100835.0  109224.0 NaN  109224.0  109224.0  109224.0  109224.0  109224.0
 110798.0  117038.0 NaN  117038.0  117038.0  117038.0  117038.0  117038.0
 111663.0  118172.0 NaN  118172.0  118172.0  118172.0  118172.0  118172.0
 181137.0  195875.0 NaN  195875.0  195875.0  195875.0  195875.0  195875.0

[4520 rows x 64 columns]

In [ ]:
csv_df.groupby('Y2016').describe()

          Unnamed: 0.1                                                   \
                 count     mean std      min      25%      50%      75%
Y2016
-3225.0            1.0  37479.0 NaN  37479.0  37479.0  37479.0  37479.0
-2051.0            1.0  37495.0 NaN  37495.0  37495.0  37495.0  37495.0
-1499.0            1.0  49834.0 NaN  49834.0  49834.0  49834.0  49834.0
-1324.0            1.0  49894.0 NaN  49894.0  49894.0  49894.0  49894.0
-1088.0            1.0  37525.0 NaN  37525.0  37525.0  37525.0  37525.0
...                ...      ...  ..      ...      ...      ...      ...
 94447.0           1.0   8859.0 NaN   8859.0   8859.0   8859.0   8859.0
 103603.0          1.0  11631.0 NaN  11631.0  11631.0  11631.0  11631.0
 116483.0          1.0  43132.0 NaN  43132.0  43132.0  43132.0  43132.0
 119330.0          1.0  43128.0 NaN  43128.0  43128.0  43128.0  43128.0
 185960.0          1.0  42972.0 NaN  42972.0  42972.0  42972.0  42972.0

                   Unnamed: 0           ...     Y2017           Y2018  \
               max      count     mean  ...       75%       max count
Y2016                                   ...
-3225.0    37479.0        1.0  37479.0  ...     689.0     689.0   1.0
-2051.0    37495.0        1.0  37495.0  ...     206.0     206.0   1.0
-1499.0    49834.0        1.0  49834.0  ...    2665.0    2665.0   1.0
-1324.0    49894.0        1.0  49894.0  ...    2555.0    2555.0   1.0
-1088.0    37525.0        1.0  37525.0  ...     457.0     457.0   1.0
...            ...        ...      ...  ...       ...       ...   ...
 94447.0    8859.0        1.0   8859.0  ...   96443.0   96443.0   1.0
 103603.0  11631.0        1.0  11631.0  ...  106400.0  106400.0   1.0
 116483.0  43132.0        1.0  43132.0  ...  112625.0  112625.0   1.0
 119330.0  43128.0        1.0  43128.0  ...  117702.0  117702.0   1.0
 185960.0  42972.0        1.0  42972.0  ...  190873.0  190873.0   1.0


               mean std       min       25%       50%       75%       max
Y2016
-3225.0       399.0 NaN     399.0     399.0     399.0     399.0     399.0
-2051.0       386.0 NaN     386.0     386.0     386.0     386.0     386.0
-1499.0      -296.0 NaN    -296.0    -296.0    -296.0    -296.0    -296.0
-1324.0      -597.0 NaN    -597.0    -597.0    -597.0    -597.0    -597.0
-1088.0       116.0 NaN     116.0     116.0     116.0     116.0     116.0
...             ...  ..       ...       ...       ...       ...       ...
 94447.0    98424.0 NaN   98424.0   98424.0   98424.0   98424.0   98424.0
 103603.0  109224.0 NaN  109224.0  109224.0  109224.0  109224.0  109224.0
 116483.0  117038.0 NaN  117038.0  117038.0  117038.0  117038.0  117038.0
 119330.0  118172.0 NaN  118172.0  118172.0  118172.0  118172.0  118172.0
 185960.0  195875.0 NaN  195875.0  195875.0  195875.0  195875.0  195875.0

[4520 rows x 64 columns]

In [69]:
csv_df.groupby('Y2017').describe()

,count,mean,std,min,25%,50%,75%,max
Element,,,,,,,,
Domestic supply quantity,5258.0,397.146843,2458.711288,-144.0,0.00,6.235,81.0000,112625.00
Export Quantity,3659.0,49.832960,840.289959,0.0,0.00,0.000,3.1400,34641.00
Fat supply quantity (g/capita/day),4982.0,2.058177,7.817204,0.0,0.00,0.040,0.5075,97.13
Feed,1213.0,184.423479,1315.564296,0.0,0.00,0.200,26.0000,29580.00
Food,4912.0,256.288331,1349.587482,0.0,0.00,5.000,63.0000,51220.00
Food supply (kcal/capita/day),4965.0,91.577241,357.340628,0.0,0.00,3.000,26.0000,3457.00
Food supply quantity (kg/capita/yr),4876.0,9.985652,29.260778,0.0,0.01,0.595,5.7625,433.38
Import Quantity,4929.0,59.760416,482.217302,0.0,0.00,1.000,8.0000,18627.00
Losses,2009.0,79.947237,393.408528,0.0,0.00,4.000,31.0000,10342.00
Other uses (non-food),1619.0,56.606529,501.900270,0.0,0.00,0.000,2.0000,17219.00
Processing,1998.0,146.564565,966.799450,0.0,0.00,0.000,5.0000,22174.00
Production,3829.0,530.179391,3005.830342,0.0,0.49,15.720,152.0000,117702.00
Protein supply quantity (g/capita/day),4980.0,2.378002,8.942167,0.0,0.00,0.030,0.6400,100.10
Residuals,4618.0,7.687311,366.797995,-682.0,0.00,0.000,0.0000,17476.00
Seed,758.0,32.810211,104.959459,0.0,1.00,4.000,23.0000,1453.00
Stock Variation,4231.0,12.837842,177.842748,-1582.0,0.00,0.000,1.0000,5089.00
Total Population - Both sexes,45.0,24725.355556,34468.527183,207.0,4283.00,15017.000,29121.0000,190873.00
Tourist consumption,555.0,0.163964,0.624528,0.0,0.00,0.000,0.0000,6.00

In [ ]:
csv_df.groupby('Y2018').describe()

          Unnamed: 0.1                                                 \
                 count     mean       std      min       25%      50%
Y2018
-3396.0            1.0   8872.0       NaN   8872.0   8872.00   8872.0
-2450.0            1.0   8939.0       NaN   8939.0   8939.00   8939.0
-2156.0            2.0   9119.5  21.92031   9104.0   9111.75   9119.5
-1445.0            1.0  39031.0       NaN  39031.0  39031.00  39031.0
-1442.0            1.0  39015.0       NaN  39015.0  39015.00  39015.0
...                ...      ...       ...      ...       ...      ...
 98424.0           1.0   8859.0       NaN   8859.0   8859.00   8859.0
 109224.0          1.0  11631.0       NaN  11631.0  11631.00  11631.0
 117038.0          1.0  43132.0       NaN  43132.0  43132.00  43132.0
 118172.0          1.0  43128.0       NaN  43128.0  43128.00  43128.0
 195875.0          1.0  42972.0       NaN  42972.0  42972.00  42972.0

                             Unnamed: 0           ...     Y2016            \
                75%      max      count     mean  ...       75%       max
Y2018                                             ...
-3396.0     8872.00   8872.0        1.0   8872.0  ...     570.0     570.0
-2450.0     8939.00   8939.0        1.0   8939.0  ...    1230.0    1230.0
-2156.0     9127.25   9135.0        2.0   9119.5  ...    -985.0    -985.0
-1445.0    39031.00  39031.0        1.0  39031.0  ...     915.0     915.0
-1442.0    39015.00  39015.0        1.0  39015.0  ...     915.0     915.0
...             ...      ...        ...      ...  ...       ...       ...
 98424.0    8859.00   8859.0        1.0   8859.0  ...   94447.0   94447.0
 109224.0  11631.00  11631.0        1.0  11631.0  ...  103603.0  103603.0
 117038.0  43132.00  43132.0        1.0  43132.0  ...  116483.0  116483.0
 118172.0  43128.00  43128.0        1.0  43128.0  ...  119330.0  119330.0
 195875.0  42972.00  42972.0        1.0  42972.0  ...  185960.0  185960.0

          Y2017                                                         \
          count      mean  std       min       25%       50%       75%
Y2018
-3396.0     1.0    -157.0  NaN    -157.0    -157.0    -157.0    -157.0
-2450.0     1.0       0.0  NaN       0.0       0.0       0.0       0.0
-2156.0     2.0   -1582.0  0.0   -1582.0   -1582.0   -1582.0   -1582.0
-1445.0     1.0   -1200.0  NaN   -1200.0   -1200.0   -1200.0   -1200.0
-1442.0     1.0   -1159.0  NaN   -1159.0   -1159.0   -1159.0   -1159.0
...         ...       ...  ...       ...       ...       ...       ...
 98424.0    1.0   96443.0  NaN   96443.0   96443.0   96443.0   96443.0
 109224.0   1.0  106400.0  NaN  106400.0  106400.0  106400.0  106400.0
 117038.0   1.0  112625.0  NaN  112625.0  112625.0  112625.0  112625.0
 118172.0   1.0  117702.0  NaN  117702.0  117702.0  117702.0  117702.0
 195875.0   1.0  190873.0  NaN  190873.0  190873.0  190873.0  190873.0


                max
Y2018
-3396.0      -157.0
-2450.0         0.0
-2156.0     -1582.0
-1445.0     -1200.0
-1442.0     -1159.0
...             ...
 98424.0    96443.0
 109224.0  106400.0
 117038.0  112625.0
 118172.0  117702.0
 195875.0  190873.0

[4591 rows x 64 columns]

In [ ]:
csv_df.groupby('Y2018')['Area'].describe()

          count unique         top freq
Y2018
-3396.0       1      1       Egypt    1
-2450.0       1      1       Egypt    1
-2156.0       2      1       Egypt    2
-1445.0       1      1  Mozambique    1
-1442.0       1      1  Mozambique    1
...         ...    ...         ...  ...
 98424.0      1      1       Egypt    1
 109224.0     1      1    Ethiopia    1
 117038.0     1      1     Nigeria    1
 118172.0     1      1     Nigeria    1
 195875.0     1      1     Nigeria    1

[4591 rows x 4 columns]

In [34]:
print(csv_df.shape)

(60942, 14)

In [35]:
csv_df.groupby('Element Code').describe()

             Unnamed: 0.1                                                 \
                    count          mean           std      min       25%
Element Code
1000 tonnes           1.0  22377.000000           NaN  22377.0  22377.00
5072               4232.0  30628.068053  17697.628084     13.0  15072.75
511                  45.0  29498.400000  17791.564368      0.0  14362.00
5123               2009.0  31003.154803  17688.945273     18.0  15961.00
5131               2010.0  30808.225871  17506.301247     19.0  17436.50
5142               4941.0  30470.311880  17518.898976     22.0  15261.00
5154               1732.0  31167.591224  17919.707532     20.0  15470.25
5170               4655.0  30250.140279  17536.502826     21.0  14982.00
5171                555.0  21995.459459  15323.266683   1724.0   7349.00
5301               5295.0  30338.044759  17556.434612      1.0  15006.50
5511               3880.0  31148.207216  17609.967855     11.0  16661.75
5521               1319.0  29710.784685  17794.143753     16.0  13487.00
5527                762.0  30359.628609  17869.761263     17.0  15392.50
5611               5139.0  30326.628527  17566.671792     12.0  14934.50
5911               4401.0  31012.762554  17759.574168     14.0  15292.00
645                4905.0  30434.688277  17518.357114     23.0  15238.00
664                5014.0  30479.601316  17525.501005      2.0  15254.00
674                5023.0  30451.665539  17527.085919      3.0  15231.50
684                5023.0  30452.665539  17527.085919      4.0  15232.50

                                         Unnamed: 0                ...  \
                  50%       75%      max      count          mean  ...
Element Code                                                       ...
1000 tonnes   22377.0  22377.00  22377.0        1.0  22377.000000  ...
5072          31163.5  46036.00  60933.0     4232.0  30628.068053  ...
511           29508.0  44446.00  59549.0       45.0  29498.400000  ...
5123          31441.0  46585.00  60801.0     2009.0  31003.154803  ...
5131          30956.5  44919.25  60802.0     2010.0  30808.225871  ...
5142          30306.0  45788.00  60937.0     4941.0  30470.311880  ...
5154          32006.5  47025.50  60906.0     1732.0  31167.591224  ...
5170          30057.0  45457.00  60936.0     4655.0  30250.140279  ...
5171          15405.0  36627.50  47042.0      555.0  21995.459459  ...
5301          30161.0  45679.00  60935.0     5295.0  30338.044759  ...
5511          31366.5  46688.00  60861.0     3880.0  31148.207216  ...
5521          29273.0  44741.50  60844.0     1319.0  29710.784685  ...
5527          30858.0  45843.75  60772.0      762.0  30359.628609  ...
5611          30201.0  45620.00  60932.0     5139.0  30326.628527  ...
5911          31552.0  46596.00  60934.0     4401.0  31012.762554  ...
645           30291.0  45670.00  60938.0     4905.0  30434.688277  ...
664           30356.0  45735.75  60939.0     5014.0  30479.601316  ...
674           30319.0  45707.50  60940.0     5023.0  30451.665539  ...
684           30320.0  45708.50  60941.0     5023.0  30452.665539  ...

                   Y2017              Y2018                              \
                     75%        max   count          mean           std
Element Code
1000 tonnes          NaN        NaN     0.0           NaN           NaN
5072              1.0000    5089.00  4217.0      4.879751    132.428693
511           29121.0000  190873.00    45.0  25346.777778  35337.267187
5123             31.0000   10342.00  2008.0     81.624502    402.263215
5131              5.0000   22174.00  2003.0    153.983525   1022.278276
5142             63.0000   51220.00  4913.0    265.385972   1407.952979
5154              2.0000   17219.00  1655.0     55.166749    497.694277
5170              0.0000   17476.00  4616.0      7.552860    363.873325
5171              0.0000       6.00   555.0      0.162162      0.617736
5301             81.0000  112625.00  5256.0    411.185712   2544.664930
5511            152.0000  117702.00  3846.0    539.540533   3019.990719
5521             26.0000   29580.00  1225.0    190.603820   1382.718629
5527             23.0000    1453.00   758.0     33.328681    105.787366
5611              8.0000   18627.00  4945.0     58.240059    467.670555
5911              3.1400   34641.00  3645.0     49.820247    842.748656
645               5.7625     433.38  4877.0     10.058817     29.555214
664              26.0000    3457.00  4969.0     91.620246    357.469150
674               0.6400     100.10  4986.0      2.373357      8.933189
684               0.5075      97.13  4987.0      2.057086      7.799864


                 min        25%       50%         75%        max
Element Code
1000 tonnes      NaN        NaN       NaN         NaN        NaN
5072         -3396.0     0.0000      0.00      0.0000    2226.00
511            211.0  4403.0000  15478.00  29767.0000  195875.00
5123             0.0     0.0000      4.00     31.0000   10355.00
5131             0.0     0.0000      0.00      5.0000   22609.00
5142             0.0     0.0000      5.38     63.8800   54077.00
5154             0.0     0.0000      0.00      2.0000   17221.00
5170          -598.0     0.0000      0.00      0.0000   17323.00
5171             0.0     0.0000      0.00      0.0000       6.00
5301          -184.0     0.0000      7.00     82.0000  117038.00
5511             0.0     0.1625     16.00    153.7500  118172.00
5521             0.0     0.0000      0.20     24.0000   31567.00
5527             0.0     1.0000      4.00     22.7500    1474.00
5611             0.0     0.0000      0.48      8.0000   18036.00
5911             0.0     0.0000      0.00      3.0000   34641.00
645              0.0     0.0100      0.60      5.6900     443.56
664              0.0     0.0000      3.00     26.0000    3450.00
674              0.0     0.0000      0.03      0.6475     101.08
684              0.0     0.0000      0.03      0.4900      94.94

[19 rows x 72 columns]

In [43]:
csv_df.groupby('Area').sum()

<ipython-input-43-b96fb15fef6a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  csv_df.groupby('Area').sum()

,Unnamed: 0.1,Unnamed: 0,Area Code,Item Code,Y2014,Y2015,Y2016,Y2017,Y2018
Area,,,,,,,,,
Algeria,861328,861328,5252,3532053,313375.33,324058.40,326007.41,325644.27,341729.98
Angola,2882888,2882888,9968,3819908,208584.42,209565.67,214725.32,229159.57,235206.68
Benin,4342015,4342015,68105,3453692,118050.79,108181.13,117963.59,124771.22,124960.70
Botswana,6491069,6491069,27560,3704902,22339.92,23024.85,22970.65,22101.30,23129.08
Burkina Faso,8600536,8600536,328297,3778795,105051.33,102701.22,107702.27,101855.07,112970.72
Cabo Verde,13706378,13706378,44065,3394130,14576.94,14538.93,14569.40,14650.74,14622.60
Cameroon,23811870,23811870,46720,3916078,217630.28,225220.72,231714.36,232030.43,233022.93
Central African Republic,23804256,23804256,49728,3607546,28739.02,28885.34,29454.54,29937.00,30101.57
Chad,25590865,25590865,52377,3606529,65940.17,65835.88,72673.76,71594.68,72282.24
"Citrus, Other",22377,22377,1014,5911,0.00,0.00,0.00,0.00,0.00
Comoros,888705,888705,2025,124514,32.00,41.34,54.91,59.84,59.84
Congo,28935414,28935414,64998,3792029,38699.26,40255.51,40592.66,41181.68,42005.53
CÃÂ´te d'Ivoire,28052017,28052017,156862,3932082,195982.84,211591.29,211439.20,224599.01,227018.00
Djibouti,9100545,9100545,78840,2956078,21332.28,23690.16,21783.91,22729.91,23718.96
Egypt,14288520,14288520,87792,3996567,849192.30,868218.73,858568.63,866379.92,852652.92
Eswatini,14109234,14109234,268356,3456174,53285.75,54072.07,54025.21,54343.33,55045.07
Ethiopia,17876238,17876238,344386,3878162,415935.50,429139.33,444567.57,448683.76,450788.86
Ethiopia PDR,510783,510783,2418,107853,0.00,0.00,0.00,0.00,0.00
Gabon,17105055,17105055,92130,3354410,28126.31,28367.30,28129.95,27979.64,28339.38
Gambia,21350872,21350872,87600,3402788,19607.87,19665.39,21758.15,23154.18,23513.80
Ghana,31930705,31930705,109674,3639339,308328.59,311092.13,314320.45,337599.06,358915.64
Guinea,35199945,35199945,126900,3782145,91213.40,92803.39,95450.24,98138.87,103262.08
Guinea-Bissau,29591388,29591388,197400,3035574,17708.67,17990.06,18524.83,19102.77,18997.92
Kenya,43020900,43020900,177840,4185637,255211.01,265506.19,260257.56,264660.66,270916.80
Lesotho,33272375,33272375,140300,3099348,19125.89,17965.84,17258.96,21267.96,19109.23
Liberia,36313263,36313263,148338,3249929,27898.35,28698.10,29746.68,29342.20,29629.83
Madagascar,45232087,45232087,185631,3864258,128985.32,126674.90,129010.25,131197.73,134576.44
Malawi,47571572,47571572,188110,3879389,173454.86,167989.09,164970.42,181098.71,187366.09
Mali,44280078,44280078,171969,3469876,123038.75,132456.58,147324.78,149928.33,159026.42
Mauritania,42410550,42410550,162520,3222107,109557.63,61909.99,79872.42,156665.46,157479.95
Mauritius,50678017,50678017,188786,3711587,50898.12,53372.42,49272.41,51114.83,47150.91
Morocco,53159666,53159666,199199,3743082,375977.76,412473.80,367884.18,388495.36,399271.27
Mozambique,56469244,56469244,205488,3830309,160757.87,158231.17,159924.41,161407.98,164934.05
Namibia,52509341,52509341,188601,3452725,32026.42,30687.90,30389.07,29874.89,29350.04
Niger,59304810,59304810,221674,3763737,108236.65,117834.65,123601.88,126707.58,133982.86
Nigeria,64426329,64426329,234366,3954357,1399542.19,1414362.83,1482945.71,1483268.23,1499774.24
Rwanda,64396021,64396021,262384,3824085,70001.38,70138.83,70921.76,73663.69,74839.08
Sao Tome and Principe,54683420,54683420,227161,3168050,12458.64,12386.93,12647.56,12662.63,12806.49
Senegal,69853629,69853629,285090,3922180,78533.93,91939.14,89017.72,95681.15,95493.82
Seychelles,3301026,3301026,13328,188266,305.20,358.20,416.32,442.34,442.34
Sierra Leone,61105779,61105779,244674,3343306,62570.89,62523.14,52767.72,55311.33,55981.73
South Africa,70677480,70677480,282598,3759379,497289.52,468352.18,462224.16,517590.54,509787.97
Sudan,68270790,68270790,363216,3534661,247577.56,230652.54,253197.29,239931.92,268054.39
Sudan (former),2785786,2785786,10918,146631,0.00,0.00,0.00,0.00,0.00
Togo,68886737,68886737,280798,3478828,47618.05,47834.59,47930.75,49841.88,54872.00
Tunisia,72989907,72989907,297036,3602818,117029.33,128211.41,123778.86,124167.20,127343.17
Uganda,81574371,81574371,329508,3909109,218142.33,220615.72,202981.34,213950.38,222147.25
United Republic of Tanzania,81433572,81433572,305085,3809549,337430.64,341969.46,333765.86,322616.85,349763.41
Zambia,85352173,85352173,364201,3892801,99318.53,96214.00,97728.69,103223.77,101604.27
Zimbabwe,83921285,83921285,252133,3739292,78366.34,74041.79,75638.88,75919.34,76581.41

In [57]:
csv_df.groupby('Y2015')['Element'].describe()

          count unique                            top freq
Y2015
-3161.0       1      1                Stock Variation    1
-2152.0       1      1                Stock Variation    1
-1284.0       1      1                Stock Variation    1
-907.0        1      1                Stock Variation    1
-887.0        1      1                Stock Variation    1
...         ...    ...                            ...  ...
 92443.0      1      1  Total Population - Both sexes    1
 100835.0     1      1  Total Population - Both sexes    1
 110798.0     1      1       Domestic supply quantity    1
 111663.0     1      1                     Production    1
 181137.0     1      1  Total Population - Both sexes    1

[4520 rows x 4 columns]

In [84]:
csv_df.groupby('Item').sum()

TypeError: ignored

In [83]:
csv_df.groupby('Item').describe(include='all')

                    Unnamed: 0.1                                              \
                           count unique top freq          mean           std
Item
Alcohol, Non-Food          283.0    NaN NaN  NaN  31220.855124  17418.424078
Alcoholic Beverages        564.0    NaN NaN  NaN  30738.260638  17338.551640
Animal Products            135.0    NaN NaN  NaN  29507.400000  17658.292365
Animal fats                639.0    NaN NaN  NaN  30715.414710  17665.218993
Apples and products        517.0    NaN NaN  NaN  30785.117988  17404.689099
...                          ...    ...  ..  ...           ...           ...
Vegetables, Other          583.0    NaN NaN  NaN  30119.790738  17585.106490
Vegetal Products           135.0    NaN NaN  NaN  29504.400000  17658.292365
Wheat and products         653.0    NaN NaN  NaN  29490.474732  17765.098026
Wine                       497.0    NaN NaN  NaN  30803.223340  17382.277451
Yams                       383.0    NaN NaN  NaN  28839.326371  16397.417293

                                                          ...  Y2018           \
                        min       25%      50%       75%  ... unique top freq
Item                                                      ...
Alcohol, Non-Food     961.0  16679.50  31783.0  45531.50  ...    NaN NaN  NaN
Alcoholic Beverages   903.0  16620.75  30325.5  45474.25  ...    NaN NaN  NaN
Animal Products         8.0  14370.50  29517.0  44455.50  ...    NaN NaN  NaN
Animal fats          1057.0  15331.50  30477.0  45636.50  ...    NaN NaN  NaN
Apples and products   745.0  16449.00  30187.0  45312.00  ...    NaN NaN  NaN
...                     ...       ...      ...       ...  ...    ...  ..  ...
Vegetables, Other     652.0  14952.50  30101.0  45208.50  ...    NaN NaN  NaN
Vegetal Products        5.0  14367.50  29514.0  44452.50  ...    NaN NaN  NaN
Wheat and products     27.0  13155.00  29544.0  44481.00  ...    NaN NaN  NaN
Wine                  916.0  16633.00  30339.0  45488.00  ...    NaN NaN  NaN
Yams                  191.0  15796.50  27034.0  43195.50  ...    NaN NaN  NaN

                                                                        \
                           mean          std      min      25%     50%
Item
Alcohol, Non-Food      8.399267    25.815200    -5.00   0.0000   0.000
Alcoholic Beverages  174.415811   569.973316  -499.00   0.0000   7.000
Animal Products       85.767481   119.769322     4.72  11.5250  20.940
Animal fats          423.975267  3414.186733    -3.00   0.0000   0.765
Apples and products   18.977382    98.883409    -1.00   0.0000   0.000
...                         ...          ...      ...      ...     ...
Vegetables, Other    284.700017  1112.231852   -71.00   0.1875   9.000
Vegetal Products     798.336222  1088.118590    15.10  41.8500  51.370
Wheat and products   375.031206  1452.472453 -1000.00   0.0000  10.000
Wine                   8.294292    59.286697  -135.00   0.0000   0.000
Yams                 658.547887  4212.762324  -242.00   0.0000   1.000


                           75%      max
Item
Alcohol, Non-Food       5.0000    195.0
Alcoholic Beverages    63.0000   4108.0
Animal Products       130.5000    494.0
Animal fats             7.2500  51864.0
Apples and products     2.4225    910.0
...                        ...      ...
Vegetables, Other      59.2500  11536.0
Vegetal Products     2049.0000   3077.0
Wheat and products    135.5000  17683.0
Wine                    2.0000    936.0
Yams                   43.5000  50000.0

[120 rows x 143 columns]

In [49]:
 csv_df.groupby('Unit').describe()

                Unnamed: 0.1                                              \
                       count          mean           std   min       25%
Unit
1000 persons            45.0  29498.400000  17791.564368   0.0  14362.00
1000 tonnes          40930.0  30479.821231  17626.709044   1.0  15235.25
g/capita/day         10046.0  30452.165539  17526.213476   3.0  15228.00
kcal/capita/day       5014.0  30479.601316  17525.501005   2.0  15254.00
kg                    4905.0  30434.688277  17518.357114  23.0  15238.00

                                            Unnamed: 0                ...  \
                     50%       75%      max      count          mean  ...
Unit                                                                  ...
1000 persons     29508.0  44446.00  59549.0       45.0  29498.400000  ...
1000 tonnes      30560.5  45706.75  60937.0    40930.0  30479.821231  ...
g/capita/day     30319.5  45711.00  60941.0    10046.0  30452.165539  ...
kcal/capita/day  30356.0  45735.75  60939.0     5014.0  30479.601316  ...
kg               30291.0  45670.00  60938.0     4905.0  30434.688277  ...

                      Y2017               Y2018                              \
                        75%        max    count          mean           std
Unit
1000 persons     29121.0000  190873.00     45.0  25346.777778  35337.267187
1000 tonnes         15.0000  117702.00  39642.0    173.745393   1503.906463
g/capita/day         0.5700     100.10   9973.0      2.215206      8.386709
kcal/capita/day     26.0000    3457.00   4969.0     91.620246    357.469150
kg                   5.7625     433.38   4877.0     10.058817     29.555214


                    min      25%       50%       75%        max
Unit
1000 persons      211.0  4403.00  15478.00  29767.00  195875.00
1000 tonnes     -3396.0     0.00      0.00     15.00  118172.00
g/capita/day        0.0     0.00      0.03      0.57     101.08
kcal/capita/day     0.0     0.00      3.00     26.00    3450.00
kg                  0.0     0.01      0.60      5.69     443.56

[5 rows x 72 columns]

In [59]:
 csv_df.groupby('Element')['Y2015'].describe()

,count,mean,std,min,25%,50%,75%,max
Element,,,,,,,,
Domestic supply quantity,5245.0,385.413451,2400.248993,-122.0,0.00,6.00,79.000,110798.00
Export Quantity,3703.0,42.563994,910.217891,0.0,0.00,0.00,2.965,52578.00
Fat supply quantity (g/capita/day),4974.0,2.057849,7.801911,0.0,0.00,0.03,0.500,96.79
Feed,1177.0,191.206644,1373.447354,0.0,0.00,0.70,26.000,30472.00
Food,4901.0,251.450949,1329.720375,0.0,0.00,5.00,61.000,50705.00
Food supply (kcal/capita/day),4955.0,91.500101,356.076420,0.0,0.00,3.00,26.500,3454.00
Food supply quantity (kg/capita/yr),4865.0,10.142884,29.625873,0.0,0.01,0.62,5.680,418.21
Import Quantity,4911.0,54.371505,467.826618,0.0,0.00,0.78,8.000,18824.00
Losses,2009.0,77.371329,376.049594,0.0,0.00,4.00,30.000,9999.00
Other uses (non-food),1667.0,39.744697,240.789221,0.0,0.00,0.00,2.000,6001.00
Processing,1995.0,144.325313,920.450961,0.0,0.00,0.00,5.000,21609.00
Production,3828.0,508.625755,2839.606113,0.0,0.17,15.00,144.250,111663.00
Protein supply quantity (g/capita/day),4971.0,2.380597,8.932136,0.0,0.00,0.03,0.680,100.33
Residuals,4605.0,6.524430,337.553668,-559.0,0.00,0.00,0.000,16136.00
Seed,759.0,31.590013,100.327105,0.0,1.00,3.00,20.500,1352.00
Stock Variation,4229.0,8.255141,144.911156,-3161.0,0.00,0.00,1.000,3418.00
Total Population - Both sexes,45.0,23512.911111,32767.324536,199.0,4046.00,14111.00,27849.000,181137.00
Tourist consumption,555.0,0.628829,3.348996,0.0,0.00,0.00,0.000,48.00

In [62]:
csv_df.groupby('Element')['Y2015'].sum()

Element
Domestic supply quantity                  2021493.55
Export Quantity                            157614.47
Fat supply quantity (g/capita/day)          10235.74
Feed                                       225050.22
Food                                      1232361.10
Food supply (kcal/capita/day)              453383.00
Food supply quantity (kg/capita/yr)         49345.13
Import Quantity                            267018.46
Losses                                     155439.00
Other uses (non-food)                       66254.41
Processing                                 287929.00
Production                                1947019.39
Protein supply quantity (g/capita/day)      11833.95
Residuals                                   30045.00
Seed                                        23976.82
Stock Variation                             34910.99
Total Population - Both sexes             1058081.00
Tourist consumption                           349.00
Name: Y2015, dtype: float64

In [63]:
csv_df.groupby('Element')['Y2017'].sum()

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [70]:
csv_df.groupby('Element')['Y2017'].describe(include='all')

,count,mean,std,min,25%,50%,75%,max
Element,,,,,,,,
Domestic supply quantity,5258.0,397.146843,2458.711288,-144.0,0.00,6.235,81.0000,112625.00
Export Quantity,3659.0,49.832960,840.289959,0.0,0.00,0.000,3.1400,34641.00
Fat supply quantity (g/capita/day),4982.0,2.058177,7.817204,0.0,0.00,0.040,0.5075,97.13
Feed,1213.0,184.423479,1315.564296,0.0,0.00,0.200,26.0000,29580.00
Food,4912.0,256.288331,1349.587482,0.0,0.00,5.000,63.0000,51220.00
Food supply (kcal/capita/day),4965.0,91.577241,357.340628,0.0,0.00,3.000,26.0000,3457.00
Food supply quantity (kg/capita/yr),4876.0,9.985652,29.260778,0.0,0.01,0.595,5.7625,433.38
Import Quantity,4929.0,59.760416,482.217302,0.0,0.00,1.000,8.0000,18627.00
Losses,2009.0,79.947237,393.408528,0.0,0.00,4.000,31.0000,10342.00
Other uses (non-food),1619.0,56.606529,501.900270,0.0,0.00,0.000,2.0000,17219.00
Processing,1998.0,146.564565,966.799450,0.0,0.00,0.000,5.0000,22174.00
Production,3829.0,530.179391,3005.830342,0.0,0.49,15.720,152.0000,117702.00
Protein supply quantity (g/capita/day),4980.0,2.378002,8.942167,0.0,0.00,0.030,0.6400,100.10
Residuals,4618.0,7.687311,366.797995,-682.0,0.00,0.000,0.0000,17476.00
Seed,758.0,32.810211,104.959459,0.0,1.00,4.000,23.0000,1453.00
Stock Variation,4231.0,12.837842,177.842748,-1582.0,0.00,0.000,1.0000,5089.00
Total Population - Both sexes,45.0,24725.355556,34468.527183,207.0,4283.00,15017.000,29121.0000,190873.00
Tourist consumption,555.0,0.163964,0.624528,0.0,0.00,0.000,0.0000,6.00

In [71]:
csv_df.describe(include='all')b

,Unnamed: 0.1,Unnamed: 0,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
count,60942.000000,60942.000000,60942.000000,60942,60942.000000,60941,60941,60940,60940,59354.000000,59394.000000,59405.000000,59436.000000,59506.000000
unique,NaN,NaN,NaN,50,NaN,120,19,18,5,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,Kenya,NaN,Milk - Excluding Butter,5301,Domestic supply quantity,1000 tonnes,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,1560,NaN,1262,5295,5295,40930,NaN,NaN,NaN,NaN,NaN
mean,30470.500000,30470.500000,134.282088,NaN,2691.453431,NaN,NaN,NaN,NaN,134.196282,135.238243,136.562119,140.920136,143.760797
std,17592.584389,17592.584389,72.692510,NaN,1052.588963,NaN,NaN,NaN,NaN,1567.663696,1603.417386,1640.048318,1671.876324,1710.796932
min,0.000000,0.000000,4.000000,NaN,2501.000000,NaN,NaN,NaN,NaN,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,15235.250000,15235.250000,74.000000,NaN,2562.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,30470.500000,30470.500000,136.000000,NaN,2630.000000,NaN,NaN,NaN,NaN,0.090000,0.080000,0.080000,0.100000,0.070000
75%,45705.750000,45705.750000,195.000000,NaN,2775.000000,NaN,NaN,NaN,NaN,8.340000,8.460000,8.430000,9.000000,9.000000
max,60941.000000,60941.000000,1014.000000,NaN,260000.000000,NaN,NaN,NaN,NaN,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [72]:
my_tuppy = (1,2,5,8)
my_tuppy[2] = 6

print(my_tuppy)

TypeError: ignored

In [74]:
s = [['him','sell'],[90,28,43]]

print(s[0][1][1])

e

In [76]:
csv_df.groupby('Area')['Area'].sum()

Area
Algeria                        AlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlgeriaAlge...
Angola                         AngolaAngolaAngolaAngolaAngolaAngolaAngolaAngo...
Benin                          BeninBeninBeninBeninBeninBeninBeninBeninBeninB...
Botswana                       BotswanaBotswanaBotswanaBotswanaBotswanaBotswa...
Burkina Faso                   Burkina FasoBurkina FasoBurkina FasoBurkina Fa...
Cabo Verde                     Cabo VerdeCabo VerdeCabo VerdeCabo VerdeCabo V...
Cameroon                       CameroonCameroonCameroonCameroonCameroonCamero...
Central African Republic       Central African RepublicCentral African Republ...
Chad                           ChadChadChadChadChadChadChadChadChadChadChadCh...
Citrus, Other                                                      Citrus, Other
Comoros                        ComorosComorosComorosComorosComorosComorosComo...
Congo                          CongoCongoCongoCongoCongoCongoCongoCongoCongoC...
CÃÂ´te d'Ivoire               CÃÂ´te d'IvoireCÃÂ´te d'IvoireCÃÂ´te d'Ivoi...
Djibouti                       DjiboutiDjiboutiDjiboutiDjiboutiDjiboutiDjibou...
Egypt                          EgyptEgyptEgyptEgyptEgyptEgyptEgyptEgyptEgyptE...
Eswatini                       EswatiniEswatiniEswatiniEswatiniEswatiniEswati...
Ethiopia                       EthiopiaEthiopiaEthiopiaEthiopiaEthiopiaEthiop...
Ethiopia PDR                   Ethiopia PDREthiopia PDREthiopia PDREthiopia P...
Gabon                          GabonGabonGabonGabonGabonGabonGabonGabonGabonG...
Gambia                         GambiaGambiaGambiaGambiaGambiaGambiaGambiaGamb...
Ghana                          GhanaGhanaGhanaGhanaGhanaGhanaGhanaGhanaGhanaG...
Guinea                         GuineaGuineaGuineaGuineaGuineaGuineaGuineaGuin...
Guinea-Bissau                  Guinea-BissauGuinea-BissauGuinea-BissauGuinea-...
Kenya                          KenyaKenyaKenyaKenyaKenyaKenyaKenyaKenyaKenyaK...
Lesotho                        LesothoLesothoLesothoLesothoLesothoLesothoLeso...
Liberia                        LiberiaLiberiaLiberiaLiberiaLiberiaLiberiaLibe...
Madagascar                     MadagascarMadagascarMadagascarMadagascarMadaga...
Malawi                         MalawiMalawiMalawiMalawiMalawiMalawiMalawiMala...
Mali                           MaliMaliMaliMaliMaliMaliMaliMaliMaliMaliMaliMa...
Mauritania                     MauritaniaMauritaniaMauritaniaMauritaniaMaurit...
Mauritius                      MauritiusMauritiusMauritiusMauritiusMauritiusM...
Morocco                        MoroccoMoroccoMoroccoMoroccoMoroccoMoroccoMoro...
Mozambique                     MozambiqueMozambiqueMozambiqueMozambiqueMozamb...
Namibia                        NamibiaNamibiaNamibiaNamibiaNamibiaNamibiaNami...
Niger                          NigerNigerNigerNigerNigerNigerNigerNigerNigerN...
Nigeria                        NigeriaNigeriaNigeriaNigeriaNigeriaNigeriaNige...
Rwanda                         RwandaRwandaRwandaRwandaRwandaRwandaRwandaRwan...
Sao Tome and Principe          Sao Tome and PrincipeSao Tome and PrincipeSao ...
Senegal                        SenegalSenegalSenegalSenegalSenegalSenegalSene...
Seychelles                     SeychellesSeychellesSeychellesSeychellesSeyche...
Sierra Leone                   Sierra LeoneSierra LeoneSierra LeoneSierra Leo...
South Africa                   South AfricaSouth AfricaSouth AfricaSouth Afri...
Sudan                          SudanSudanSudanSudanSudanSudanSudanSudanSudanS...
Sudan (former)                 Sudan (former)Sudan (former)Sudan (former)Suda...
Togo                           TogoTogoTogoTogoTogoTogoTogoTogoTogoTogoTogoTo...
Tunisia                        TunisiaTunisiaTunisiaTunisiaTunisiaTunisiaTuni...
Uganda                         UgandaUgandaUgandaUgandaUgandaUgandaUgandaUgan...
United Republic of Tanzania    United Republic of TanzaniaUnited Republic of ...
Zambia                         ZambiaZambiaZambiaZambiaZambiaZambiaZambiaZamb...
Zimbabwe                       ZimbabweZimbabweZimbabweZimbabweZimbabweZimbab...
Name: Area, dtype: object

In [82]:
csv_df.groupby('Area')['Element','Y2015'].describe()

<ipython-input-82-69d76b5ad8ff>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  csv_df.groupby('Area')['Element','Y2015'].describe()

                              Y2015                                        \
                              count        mean          std     min  25%
Area
Algeria                      1268.0  255.566562  1520.753940   -19.0  0.0
Angola                       1378.0  152.079586  1007.390589  -114.0  0.0
Benin                        1260.0   85.858040   483.166264  -161.0  0.0
Botswana                     1369.0   16.818736   112.182093   -12.0  0.0
Burkina Faso                 1372.0   74.855117   587.007670  -294.0  0.0
Cabo Verde                   1229.0   11.829886   103.952025   -10.0  0.0
Cameroon                     1443.0  156.078115   856.316567  -117.0  0.0
Central African Republic     1296.0   22.288071   162.514838   -35.0  0.0
Chad                         1303.0   50.526385   429.802472  -121.0  0.0
Citrus, Other                   0.0         NaN          NaN     NaN  NaN
Comoros                        45.0    0.918667     2.675048     0.0  0.0
Congo                        1377.0   29.234212   190.645182    -2.0  0.0
CÃÂ´te d'Ivoire             1446.0  146.328693   913.424111  -208.0  0.0
Djibouti                     1058.0   22.391456   146.585794    -4.0  0.0
Egypt                        1473.0  589.422084  3493.908539  -574.0  0.0
Eswatini                     1240.0   43.606508   391.566774   -39.0  0.0
Ethiopia                     1430.0  300.097434  2958.451353  -549.0  0.0
Ethiopia PDR                   39.0    0.000000     0.000000     0.0  0.0
Gabon                        1202.0   23.600083   133.335271    -2.0  0.0
Gambia                       1115.0   17.637121   135.044596   -30.0  0.0
Ghana                        1333.0  233.377442  1582.505868   -70.0  0.0
Guinea                       1349.0   68.794211   423.100298  -186.0  0.0
Guinea-Bissau                1040.0   17.298135   119.640992    -6.0  0.0
Kenya                        1542.0  172.183003  1385.046508  -250.0  0.0
Lesotho                      1097.0   16.377247   124.532731    -7.0  0.0
Liberia                      1134.0   25.306966   175.575701    -9.0  0.0
Madagascar                   1429.0   88.645836   754.979551  -305.0  0.0
Malawi                       1400.0  119.992207   724.474890  -271.0  0.0
Mali                         1256.0  105.459061   658.313432  -559.0  0.0
Mauritania                   1152.0   53.741311   619.499842    -3.0  0.0
Mauritius                    1352.0   39.476642   299.402562   -47.0  0.0
Morocco                      1381.0  298.677625  2373.229911  -179.0  0.0
Mozambique                   1394.0  113.508730   935.665986  -184.0  0.0
Namibia                      1270.0   24.163701   133.967152    -4.0  0.0
Niger                        1367.0   86.199451   656.762839   -57.0  0.0
Nigeria                      1458.0  970.070528  7342.078109  -517.0  0.0
Rwanda                       1378.0   50.899006   381.898339  -827.0  0.0
Sao Tome and Principe        1125.0   11.010604   103.885236     0.0  0.0
Senegal                      1449.0   63.450062   457.257011   -33.0  0.0
Seychelles                     68.0    5.267647    24.059086    -1.3  0.0
Sierra Leone                 1181.0   52.940847   345.234057  -173.0  0.0
South Africa                 1395.0  335.736330  2013.642776 -3161.0  0.0
Sudan                        1260.0  183.057571  1281.238379 -1284.0  0.0
Sudan (former)                 53.0    0.000000     0.000000     0.0  0.0
Togo                         1226.0   39.016794   266.477876   -42.0  0.0
Tunisia                      1318.0   97.277246   486.920928  -154.0  0.0
Uganda                       1446.0  152.569654  1151.012595  -131.0  0.0
United Republic of Tanzania  1405.0  243.394633  1610.579518  -317.0  0.0
Zambia                       1420.0   67.756338   545.776130  -907.0  0.0
Zimbabwe                     1373.0   53.927014   453.960094  -369.0  0.0


                               50%      75%        max
Area
Algeria                      1.000  29.1175   39728.00
Angola                       0.100  16.8000   27884.00
Benin                        0.910  13.0000   10576.00
Botswana                     0.000   3.0000    2383.00
Burkina Faso                 0.010   8.3775   18111.00
Cabo Verde                   0.000   2.0000    2511.00
Cameroon                     0.270  20.5700   23298.00
Central African Republic     0.000   3.0000    4493.00
Chad                         0.000   6.0000   14111.00
Citrus, Other                  NaN      NaN        NaN
Comoros                      0.000   0.0300      11.63
Congo                        0.000   3.0000    4856.00
CÃÂ´te d'Ivoire             0.265  15.0000   23226.00
Djibouti                     0.020   2.4125    2665.00
Egypt                        2.000  49.0000   92443.00
Eswatini                     0.040   3.0000    5498.00
Ethiopia                     0.375  21.0000  100835.00
Ethiopia PDR                 0.000   0.0000       0.00
Gabon                        0.010   5.0000    2749.00
Gambia                       0.000   3.0000    2544.00
Ghana                        1.000  29.0000   27849.00
Guinea                       0.000   7.0000   11432.00
Guinea-Bissau                0.100   4.1775    2180.00
Kenya                        0.635  17.0000   47878.00
Lesotho                      0.000   2.0000    2193.00
Liberia                      0.040   4.0000    4472.00
Madagascar                   0.020   7.0000   24234.00
Malawi                       0.000   7.0000   16745.00
Mali                         0.990  17.0000   17439.00
Mauritania                   0.010   5.0000   14253.00
Mauritius                    0.070   3.0000    4009.00
Morocco                      1.910  32.0000   53546.00
Mozambique                   0.135  11.0000   27042.00
Namibia                      0.235   5.7125    2427.00
Niger                        0.000   6.0000   20002.00
Nigeria                      0.540  49.7850  181137.00
Rwanda                       0.000   4.1650   11369.00
Sao Tome and Principe        0.000   1.0000    2369.00
Senegal                      0.030   8.0000   14578.00
Seychelles                   0.030   0.6450     160.17
Sierra Leone                 0.140   6.0000    7172.00
South Africa                 3.000  52.0200   55386.00
Sudan                        0.185  20.6750   38903.00
Sudan (former)               0.000   0.0000       0.00
Togo                         0.330   8.0000    7323.00
Tunisia                      1.260  19.0000   11180.00
Uganda                       0.020  13.0000   38225.00
United Republic of Tanzania  1.000  33.0000   51483.00
Zambia                       0.010   7.0000   15879.00
Zimbabwe                     0.130   7.0000   13815.00

In [85]:
csv_df.isnull().sum()

Unnamed: 0.1       0
Unnamed: 0         0
Area Code          0
Area               0
Item Code          0
Item               1
Element Code       1
Element            2
Unit               2
Y2014           1588
Y2015           1548
Y2016           1537
Y2017           1506
Y2018           1436
dtype: int64

In [87]:
csv_df.groupby('Item').sum()

<ipython-input-87-ce626981bcdb>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  csv_df.groupby('Item').sum()

,Unnamed: 0.1,Unnamed: 0,Area Code,Item Code,Y2014,Y2015,Y2016,Y2017,Y2018
Item,,,,,,,,,
"Alcohol, Non-Food",8835502,8835502,38447,752497,2403.00,2180.00,2223.00,2348.00,2293.00
Alcoholic Beverages,17336379,17336379,75016,1649136,102410.11,98783.72,96958.75,95581.06,97847.27
Animal Products,3983499,3983499,18060,397035,11935.65,11811.73,11661.69,11547.65,11578.61
Animal fats,19627150,19627150,85279,1882494,209460.54,200675.72,183314.22,269617.53,269648.27
Apples and products,15915906,15915906,69280,1352989,9499.23,10559.15,9853.26,10198.90,9640.51
...,...,...,...,...,...,...,...,...,...
"Vegetables, Other",17559838,17559838,77779,1518715,155038.96,158104.08,156218.90,157752.59,163987.21
Vegetal Products,3983094,3983094,18060,391905,107145.19,107064.17,106792.72,107655.20,107775.39
Wheat and products,19257280,19257280,87073,1639683,232670.13,234710.51,239377.07,240047.62,242645.19
Wine,15309202,15309202,66206,1319535,4497.36,4251.81,3872.09,4178.02,4039.32
Yams,11045462,11045462,50798,970905,200396.96,203151.78,220626.20,229174.59,221272.09

In [96]:
csv_df.groupby('Area')['Y2017'].sum()

Area
Algeria                         325644.27
Angola                          229159.57
Benin                           124771.22
Botswana                         22101.30
Burkina Faso                    101855.07
Cabo Verde                       14650.74
Cameroon                        232030.43
Central African Republic         29937.00
Chad                             71594.68
Citrus, Other                        0.00
Comoros                             59.84
Congo                            41181.68
CÃÂ´te d'Ivoire                224599.01
Djibouti                         22729.91
Egypt                           866379.92
Eswatini                         54343.33
Ethiopia                        448683.76
Ethiopia PDR                         0.00
Gabon                            27979.64
Gambia                           23154.18
Ghana                           337599.06
Guinea                           98138.87
Guinea-Bissau                    19102.77
Kenya                           264660.66
Lesotho                          21267.96
Liberia                          29342.20
Madagascar                      131197.73
Malawi                          181098.71
Mali                            149928.33
Mauritania                      156665.46
Mauritius                        51114.83
Morocco                         388495.36
Mozambique                      161407.98
Namibia                          29874.89
Niger                           126707.58
Nigeria                        1483268.23
Rwanda                           73663.69
Sao Tome and Principe            12662.63
Senegal                          95681.15
Seychelles                         442.34
Sierra Leone                     55311.33
South Africa                    517590.54
Sudan                           239931.92
Sudan (former)                       0.00
Togo                             49841.88
Tunisia                         124167.20
Uganda                          213950.38
United Republic of Tanzania     322616.85
Zambia                          103223.77
Zimbabwe                         75919.34
Name: Y2017, dtype: float64

In [99]:
csv_df.groupby('Element').sum()

<ipython-input-99-ba73ceef1729>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  csv_df.groupby('Element').sum()

,Unnamed: 0.1,Unnamed: 0,Area Code,Item Code,Y2014,Y2015,Y2016,Y2017,Y2018
Element,,,,,,,,,
Domestic supply quantity,160639947,160639947,708993,14197445,1996716.35,2021493.55,2044842.70,2088198.10,2161192.10
Export Quantity,136487168,136487168,599728,11835203,150020.64,157614.47,151920.46,182338.80,181594.80
Fat supply quantity (g/capita/day),152963739,152963739,675050,13535000,10225.56,10235.74,10102.77,10253.84,10258.69
Feed,39188525,39188525,176272,3538507,216927.89,225050.22,228958.65,223705.68,233489.68
Food,150553811,150553811,663295,13285035,1212332.49,1232361.10,1247022.17,1258888.28,1303841.28
Food supply (kcal/capita/day),152824721,152824721,674057,13511060,454257.00,453383.00,451810.00,454681.00,455261.00
Food supply quantity (kg/capita/yr),149282146,149282146,658446,13185401,49650.63,49345.13,48985.28,48690.04,49056.85
Import Quantity,155848544,155848544,688174,13795966,274144.48,267018.46,286582.78,294559.09,287997.09
Losses,62285338,62285338,274353,5424803,153223.00,155439.00,157787.00,160614.00,163902.00
Other uses (non-food),53982268,53982268,235554,4729749,78718.13,66254.41,69563.68,91645.97,91300.97
Processing,61924534,61924534,271940,5350416,282923.00,287929.00,280631.00,292836.00,308429.00
Production,120855044,120855044,526716,10447437,1931287.75,1947019.39,1943537.15,2030056.89,2075072.89
Protein supply quantity (g/capita/day),152958716,152958716,675050,13535000,11836.46,11833.95,11779.69,11842.45,11833.56
Residuals,140814403,140814403,623271,12421089,30149.00,30045.00,37224.00,35500.00,34864.00
Seed,23134037,23134037,103537,2035933,21922.92,23976.82,23389.20,24870.14,25263.14
Stock Variation,129617984,129617984,571566,11329527,58749.83,34910.99,33140.12,54316.91,20577.91
Total Population - Both sexes,1327428,1327428,6020,112545,1031585.00,1058081.00,1085107.00,1112641.00,1140605.00
Tourist consumption,12207480,12207480,50308,1486528,416.00,349.00,89.00,91.00,90.00

In [ ]:
csv_df.groupby('Element').sum()